name: Deployment pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize]

jobs:
 check_health_of_website:
        runs-on: ubuntu-20.04
        steps:
            - name: Check the deployed service URL
              uses: jtalk/url-health-check-action@v4
              with:
                # Check the following URLs one by one sequentially
                url: https://full-stack-open-pokedex-solitary-haze-732.fly.dev/health
                # Follow redirects, or just report success on 3xx status codes
                follow-redirect: false # Optional, defaults to "false"
                # Fail this action after this many failed attempts
                max-attempts: 3 # Optional, defaults to 1
                # Delay between retries
                retry-delay: 5s # Optional, only applicable to max-attempts > 1
                # Retry all errors, including 404. This option might trigger curl upgrade.
                retry-all: false # Optional, defaults to "false"
 simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Check style
        run: npm run eslint
      - run: npm run build
      - run: npm run test
      - name: Run Playwright tests
        run: npm run test:e2e
 tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install
      - run: npm run build
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'
      - name: Discord Success Message
        uses: discord-actions/message@v2
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Successful deployment (NKH 2024)"
      - name: Test Failure
        uses: discord-actions/message@v2
        if: failure()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Failed deployment (NKH 2024)"