name: Testing stuff

on:
  push:
    branches:
      - main



      
jobs:
  a_test_job_no_print:
    if: ${{!contains(join(github.event.commits.*.message), '#skip')}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - run: echo "#skip not detected"
  a_test_job_print:
    if: ${{contains(join(github.event.commits.*.message), '#skip')}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - run: echo "#skip detected"